// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnwUqTjJrShQcytUkI8J3czm-sUwefjV4',
    appId: '1:280674464083:web:c5bb533c8e2f7db37071a6',
    messagingSenderId: '280674464083',
    projectId: 'raya-9480c',
    authDomain: 'raya-9480c.firebaseapp.com',
    storageBucket: 'raya-9480c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdl_blwRBXj-pXjtkcDIY2FBS2Z-MI1fo',
    appId: '1:280674464083:android:a104eb07998086437071a6',
    messagingSenderId: '280674464083',
    projectId: 'raya-9480c',
    storageBucket: 'raya-9480c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMik3MMS8Gjuz6A2kFc6W1T0w0ynxR3bM',
    appId: '1:280674464083:ios:cfbcb2a96fcbf6a17071a6',
    messagingSenderId: '280674464083',
    projectId: 'raya-9480c',
    storageBucket: 'raya-9480c.appspot.com',
    iosClientId: '280674464083-26uhn3e60f8t0b7m8m5e4il2bhaclud3.apps.googleusercontent.com',
    iosBundleId: 'com.example.raya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMik3MMS8Gjuz6A2kFc6W1T0w0ynxR3bM',
    appId: '1:280674464083:ios:cfbcb2a96fcbf6a17071a6',
    messagingSenderId: '280674464083',
    projectId: 'raya-9480c',
    storageBucket: 'raya-9480c.appspot.com',
    iosClientId: '280674464083-26uhn3e60f8t0b7m8m5e4il2bhaclud3.apps.googleusercontent.com',
    iosBundleId: 'com.example.raya',
  );
}
